### ISSUE TITLE
java.lang.IllegalStateException: KtElement not inside KtFile: DummyHolder of type class com.intellij.psi.impl.source.JavaDummyHolder for element VALUE_PARAMETER_LIST of type class org.jetbrains.kotlin.psi.KtParameterList node = Element(VALUE_PARAMETER_LIST)

### ISSUE THREAD

**Issue by jamesrapadmi** [detekt/detekt-intellij-plugin#256] opened 2022-08-17 10:56 UTC
## Bug description
Just appeared no sure what caused it

## Environment
- detekt Idea Version: 1.21.0
- Platform Version: Chipmunk | 2021.2.1 Patch 1
- Platform Vendor: JetBrains s.r.o.
- Java Version: 11.0.12
- OS Name: Mac OS X

## Stacktrace

```
java.lang.IllegalStateException: KtElement not inside KtFile: DummyHolder of type class com.intellij.psi.impl.source.JavaDummyHolder for element VALUE_PARAMETER_LIST of type class org.jetbrains.kotlin.psi.KtParameterList node = Element(VALUE_PARAMETER_LIST)
	at org.jetbrains.kotlin.psi.KtElementImplStub.getContainingKtFile(KtElementImplStub.java:76)
	at org.jetbrains.kotlin.idea.caches.resolve.KotlinCacheServiceImpl.getContextFile(KotlinCacheServiceImpl.kt:574)
	at org.jetbrains.kotlin.idea.caches.resolve.KotlinCacheServiceImpl.filterNotInProjectSource(KotlinCacheServiceImpl.kt:560)
	at org.jetbrains.kotlin.idea.caches.resolve.KotlinCacheServiceImpl.getFacadeToAnalyzeFiles(KotlinCacheServiceImpl.kt:506)
	at org.jetbrains.kotlin.idea.caches.resolve.KotlinCacheServiceImpl.getResolutionFacade(KotlinCacheServiceImpl.kt:84)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.getResolutionFacade(resolutionApi.kt:26)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.analyze(resolutionApi.kt:127)
	at org.jetbrains.kotlin.idea.refactoring.changeSignature.ui.KotlinChangeSignatureDialog$Companion.getTypeInfo(KotlinChangeSignatureDialog.kt:460)
	at org.jetbrains.kotlin.idea.refactoring.changeSignature.ui.KotlinChangeSignatureDialog$Companion.evaluateChangeInfo(KotlinChangeSignatureDialog.kt:483)
	at org.jetbrains.kotlin.idea.refactoring.changeSignature.ui.KotlinChangeSignatureDialog$Companion.access$evaluateChangeInfo(KotlinChangeSignatureDialog.kt:406)
	at org.jetbrains.kotlin.idea.refactoring.changeSignature.ui.KotlinChangeSignatureDialog.calculateSignature(KotlinChangeSignatureDialog.kt:296)
	at com.intellij.refactoring.changeSignature.ChangeSignatureDialogBase.doUpdateSignature(ChangeSignatureDialogBase.java:605)
	at com.intellij.refactoring.changeSignature.ChangeSignatureDialogBase.updateSignatureAlarmFired(ChangeSignatureDialogBase.java:599)
	at org.jetbrains.kotlin.idea.refactoring.changeSignature.ui.KotlinChangeSignatureDialog.updateSignatureAlarmFired(KotlinChangeSignatureDialog.kt:316)
	at com.intellij.refactoring.changeSignature.ChangeSignatureDialogBase.lambda$updateSignature$0(ChangeSignatureDialogBase.java:592)
	at com.intellij.psi.impl.PsiDocumentManagerBase$4.lambda$run$0(PsiDocumentManagerBase.java:622)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by arturbosch** [comment] 2022-09-18 19:37
Duplicate of #271

**Closed by arturbosch** 2022-09-18 19:37 UTC
