### ISSUE TITLE
java.lang.AssertionError: Different tree sizes of bounds: lower = (BufferWhenMainSubscriber<(Any..Any?), (Any..Any?), (Any..Any?), (MutableCollection<in (Any..Any?)>..MutableCollection<in (Any..Any?)>?)>, 6), upper = (BufferWhenMainSubscriber<*, *, *, *>?, 5)

### ISSUE THREAD

**Issue by alaev-dev** [detekt/detekt-intellij-plugin#247] opened 2022-08-10 12:44 UTC
## Environment
- detekt Idea Version: 1.21.0
- Platform Version: 2022.2
- Platform Vendor: JetBrains s.r.o.
- Java Version: 17.0.3
- OS Name: Windows 10

## Stacktrace

```
java.lang.AssertionError: Different tree sizes of bounds: lower = (BufferWhenMainSubscriber<(Any..Any?), (Any..Any?), (Any..Any?), (MutableCollection<in (Any..Any?)>..MutableCollection<in (Any..Any?)>?)>, 6), upper = (BufferWhenMainSubscriber<*, *, *, *>?, 5)
	at org.jetbrains.kotlin.load.java.typeEnhancement.JavaTypeEnhancement.enhancePossiblyFlexible(typeEnhancement.kt:70)
	at org.jetbrains.kotlin.load.java.typeEnhancement.JavaTypeEnhancement.enhanceInflexible(typeEnhancement.kt:120)
	at org.jetbrains.kotlin.load.java.typeEnhancement.JavaTypeEnhancement.enhancePossiblyFlexible(typeEnhancement.kt:64)
	at org.jetbrains.kotlin.load.java.typeEnhancement.JavaTypeEnhancement.enhance(typeEnhancement.kt:53)
	at org.jetbrains.kotlin.load.java.typeEnhancement.SignatureEnhancement.enhance(signatureEnhancement.kt:225)
	at org.jetbrains.kotlin.load.java.typeEnhancement.SignatureEnhancement.enhance(signatureEnhancement.kt:216)
	at org.jetbrains.kotlin.load.java.typeEnhancement.SignatureEnhancement.enhance$default(signatureEnhancement.kt:206)
	at org.jetbrains.kotlin.load.java.typeEnhancement.SignatureEnhancement.enhanceSignature(signatureEnhancement.kt:127)
	at org.jetbrains.kotlin.load.java.typeEnhancement.SignatureEnhancement.enhanceSignatures(signatureEnhancement.kt:58)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:291)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:282)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedVariables(LazyJavaScope.kt:351)
	at org.jetbrains.kotlin.idea.caches.resolve.util.JavaResolutionUtils.resolveField(JavaResolveExtension.kt:114)
	at org.jetbrains.kotlin.idea.caches.resolve.util.JavaResolutionUtils.getJavaFieldDescriptor(JavaResolveExtension.kt:49)
	at org.jetbrains.kotlin.idea.caches.resolve.util.JavaResolutionUtils.getJavaMemberDescriptor(JavaResolveExtension.kt:56)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.processJvmCallablesByName(KotlinIndicesHelper.kt:308)
	at org.jetbrains.kotlin.idea.quickfix.AbstractImportFix.collectMemberCandidates(AbstractImportFix.kt:402)
	at org.jetbrains.kotlin.idea.quickfix.AbstractImportFix.fillCandidates(AbstractImportFix.kt:465)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.collectSuggestionsForName(AbstractImportFix.kt:183)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.collectSuggestions(AbstractImportFix.kt:156)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase$suggestions$1.invoke(AbstractImportFix.kt:87)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase$suggestions$1.invoke(AbstractImportFix.kt:79)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.computeSuggestions(AbstractImportFix.kt:90)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase$Factory.createAction(AbstractImportFix.kt:240)
	at org.jetbrains.kotlin.idea.quickfix.KotlinSingleIntentionActionFactory.doCreateActions(KotlinSingleIntentionActionFactory.kt:12)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActions(KotlinIntentionActionsFactory.kt:39)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActionsForAllProblems(KotlinIntentionActionsFactory.kt:21)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitorKt.createQuickFixes(AbstractKotlinHighlightVisitor.kt:338)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.createFixesMap(ElementAnnotator.kt:183)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.createFixesMap$default(ElementAnnotator.kt:178)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticsSameFactoryQuickFixes(ElementAnnotator.kt:80)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticsQuickFixes(ElementAnnotator.kt:73)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.annotateQuickFixes(AbstractKotlinHighlightVisitor.kt:222)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:157)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:63)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:221)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by arturbosch** [comment] 2022-09-18 19:47
Duplicate of #271

**Closed by arturbosch** 2022-09-18 19:47 UTC
