### ISSUE TITLE
java.lang.AssertionError: Can't find built-in class kotlin.annotation.Target

### ISSUE THREAD

**Issue by XsubinX** [detekt/detekt-intellij-plugin#192] opened 2022-06-27 14:54 UTC
## Bug description

Please include steps to reproduce expected and actual behavior.

## Environment
- detekt Idea Version: 1.21.0-RC1
- Platform Version: 2022.1.2
- Platform Vendor: JetBrains s.r.o.
- Java Version: 11.0.15
- OS Name: Mac OS X

## Stacktrace

```
java.lang.AssertionError: Can't find built-in class kotlin.annotation.Target
	at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getBuiltInClassByFqName(KotlinBuiltIns.java:217)
	at org.jetbrains.kotlin.load.java.components.JavaAnnotationDescriptor$type$2.invoke(JavaAnnotationMapper.kt:93)
	at org.jetbrains.kotlin.load.java.components.JavaAnnotationDescriptor$type$2.invoke(JavaAnnotationMapper.kt:93)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:42)
	at org.jetbrains.kotlin.load.java.components.JavaAnnotationDescriptor.getType(JavaAnnotationMapper.kt:93)
	at org.jetbrains.kotlin.load.java.components.JavaAnnotationDescriptor.getType(JavaAnnotationMapper.kt:86)
	at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getAnnotationClass(DescriptorUtils.kt:395)
	at org.jetbrains.kotlin.extensions.AnnotationBasedExtension$DefaultImpls.isASpecialAnnotation(AnnotationBasedExtension.kt:57)
	at org.jetbrains.kotlin.extensions.AnnotationBasedExtension$DefaultImpls.isASpecialAnnotation(AnnotationBasedExtension.kt:59)
	at org.jetbrains.kotlin.extensions.AnnotationBasedExtension$DefaultImpls.isASpecialAnnotation$default(AnnotationBasedExtension.kt:45)
	at org.jetbrains.kotlin.extensions.AnnotationBasedExtension$DefaultImpls.hasSpecialAnnotation(AnnotationBasedExtension.kt:33)
	at org.jetbrains.kotlin.allopen.AbstractAllOpenDeclarationAttributeAltererExtension.hasSpecialAnnotation(AllOpenDeclarationAttributeAltererExtension.kt:34)
	at org.jetbrains.kotlin.allopen.AbstractAllOpenDeclarationAttributeAltererExtension.refineDeclarationModality(AllOpenDeclarationAttributeAltererExtension.kt:51)
	at org.jetbrains.kotlin.resolve.ModifiersChecker.resolveModalityFromModifiers(ModifiersChecker.java:91)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.lambda$new$2(LazyClassDescriptor.java:148)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getModality(LazyClassDescriptor.java:578)
	at org.jetbrains.kotlin.idea.compilerPlugin.allopen.AllOpenUltraLightClassModifierExtension.interceptModalityBuilding(AllOpenUltraLightClassModifierExtension.kt:62)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassForSourceDeclaration.computeModifiers(KtLightClassForSourceDeclaration.kt:238)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass$_modifierList$2$1.invoke(ultraLightClass.kt:87)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass$_modifierList$2$1.invoke(ultraLightClass.kt:87)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass$KtUltraLightClassModifierList$modifiers$2.invoke(ultraLightClass.kt:59)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass$KtUltraLightClassModifierList$modifiers$2.invoke(ultraLightClass.kt:59)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass$KtUltraLightClassModifierList.getModifiers(ultraLightClass.kt:59)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass$KtUltraLightClassModifierList.hasModifierProperty(ultraLightClass.kt:62)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassForSourceDeclaration.hasModifierProperty(KtLightClassForSourceDeclaration.kt:257)
	at com.intellij.patterns.PsiModifierListOwnerPattern$2.lambda$accepts$0(PsiModifierListOwnerPattern.java:37)
	at com.intellij.util.containers.ContainerUtil.and(ContainerUtil.java:1990)
	at com.intellij.patterns.PsiModifierListOwnerPattern$2.accepts(PsiModifierListOwnerPattern.java:37)
	at com.intellij.patterns.PsiModifierListOwnerPattern$2.accepts(PsiModifierListOwnerPattern.java:34)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:58)
	at com.intellij.semantic.SemRegistrar.lambda$registerSemElementProvider$0(SemRegistrar.java:26)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:132)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:102)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:87)
	at com.intellij.microservices.url.inlay.UrlPathInlayHintsProvider$Companion$inlaysInElement$1.invoke(UrlPathInlayHintsProvider.kt:132)
	at com.intellij.microservices.url.inlay.UrlPathInlayHintsProvider$Companion$inlaysInElement$1.invoke(UrlPathInlayHintsProvider.kt:119)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at com.intellij.microservices.url.inlay.UrlPathInlayHintsProviderSemElementKt.selectProvidersFromGroups(UrlPathInlayHintsProviderSemElement.kt:95)
	at com.intellij.microservices.url.inlay.UrlPathInlayHintsProvider$getCollectorFor$1$collect$1.invoke(UrlPathInlayHintsProvider.kt:36)
	at com.intellij.microservices.url.inlay.UrlPathInlayHintsProvider$getCollectorFor$1$collect$1.invoke(UrlPathInlayHintsProvider.kt:33)
	at com.intellij.microservices.url.references.UrlPathContextKt.forbidExpensiveUrlContext(UrlPathContext.kt:219)
	at com.intellij.microservices.url.inlay.UrlPathInlayHintsProvider$getCollectorFor$1.collect(UrlPathInlayHintsProvider.kt:35)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:47)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:27)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by arturbosch** [comment] 2022-09-19 21:12
Duplicate of #271

**Closed by arturbosch** 2022-09-19 21:12 UTC
