### ISSUE TITLE
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())

### ISSUE THREAD

**Issue by MarianPohling** [detekt/detekt-intellij-plugin#222] opened 2022-07-26 09:30 UTC
## Bug description
It just happened after pressing the application stop button.

## Environment
- detekt Idea Version: 1.21.0
- Platform Version: 2022.1.4
- Platform Vendor: JetBrains s.r.o.
- Java Version: 11.0.15
- OS Name: Mac OS X

## Stacktrace

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:621)
	at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:32)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:340)
	at org.jetbrains.kotlin.psi.KtNamedDeclarationStub.getFqName(KtNamedDeclarationStub.java:206)
	at org.jetbrains.kotlin.psi.KtTypeParameterListOwnerStub.getFqName(KtTypeParameterListOwnerStub.java:29)
	at org.jetbrains.kotlin.analysis.decompiled.light.classes.KtLightClassForDecompiledDeclaration.equals(KtLightClassForDecompiledDeclaration.kt:216)
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
	at org.jetbrains.kotlin.analysis.decompiled.light.classes.KtLightMethodForDecompiledDeclaration.equals(KtLightMethodForDecompiledDeclaration.kt:89)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1120)
	at com.intellij.ide.actions.searcheverywhere.ml.id.SearchEverywhereMlItemIdProvider.getId(SearchEverywhereMlItemIdProvider.kt:14)
	at com.intellij.ide.actions.searcheverywhere.ml.SearchEverywhereMLStatisticsCollector.addElementFeatures(SearchEverywhereMLStatisticsCollector.kt:202)
	at com.intellij.ide.actions.searcheverywhere.ml.SearchEverywhereMLStatisticsCollector.getCollectedElementsData(SearchEverywhereMLStatisticsCollector.kt:175)
	at com.intellij.ide.actions.searcheverywhere.ml.SearchEverywhereMLStatisticsCollector.getElementsData(SearchEverywhereMLStatisticsCollector.kt:125)
	at com.intellij.ide.actions.searcheverywhere.ml.SearchEverywhereMLStatisticsCollector.access$getElementsData(SearchEverywhereMLStatisticsCollector.kt:16)
	at com.intellij.ide.actions.searcheverywhere.ml.SearchEverywhereMLStatisticsCollector$reportElements$1.run(SearchEverywhereMLStatisticsCollector.kt:108)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:206)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by arturbosch** [comment] 2022-09-19 20:58
Duplicate of #271

**Closed by arturbosch** 2022-09-19 20:58 UTC
