### ISSUE TITLE
I can`t open the settings after update to 1.0.0-RC1

### ISSUE THREAD

**Issue by Ksernik** [detekt/detekt-intellij-plugin#67] opened 2020-02-28 07:58 UTC
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

![Screenshot 2020-02-28 at 12 45 12](https://user-images.githubusercontent.com/9426994/75521525-c72d1180-5a29-11ea-82c0-7c6b9477e55e.png)

**Comment by brudaswen** [comment] 2020-02-28 09:33
Same here for
```
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by arturbosch** [comment] 2020-02-29 17:36
Thanks for the reports.
Should be related to #56 and fixed in master.
If you can, please build the master version and try it. I will upload a new test release in the next days.

**Comment by arturbosch** [comment] 2020-03-04 08:47
Please try out https://github.com/detekt/detekt-intellij-plugin/releases/tag/1.0.0-RC2-beta1 and report if it works now for you.

**Comment by brudaswen** [comment] 2020-03-04 09:29
Thanks for the beta release. I tried to build the plugin on my own. However, due to some strange Gradle error this was not successful (may be a Windows only file-lock issue).

I can confirm that the Plugin works now in 
```
Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: detekt, com.developerphil.adbidea, com.google.services.firebase
```

Thanks a lot for the fast fix!!!

**Comment by Ksernik** [comment] 2020-03-04 09:45
yes, everything works fine now, thanks!!

**Closed** 2020-03-04 09:57 UTC
Labels: bug

**Comment by arturbosch** [comment] 2020-03-05 09:54
Thank you for testing the beta! I will then upload RC2 to the plugin store. JetBrains approval takes like 2 more days.
