### ISSUE TITLE
IOException during scope with code references calculation

### ISSUE THREAD

**Issue by wittlock** [detekt/detekt-intellij-plugin#195] opened 2022-06-29 19:36 UTC
Seemingly randomly but possibly while changing between open files in IntelliJ I get notifications about this IOException. IntelliJ pops up saying the plugin has crashed. It seems to mostly work but they happen fairly frequently so it gets distracting with the notifications and flashing red light in the corner.

```
an exception during scope with code references calculation

java.io.IOException: readPrevChunkAddress:106,111,5257474,C:\Users\xxxxxxxxx\AppData\Local\JetBrains\IntelliJIdea2022.1\compile-server\bisam_202eeb5\targets\kotlin-data-container\kotlin-data-container_f99e646a\id-to-file.tab.values
    at com.intellij.util.io.PersistentHashMapValueStorage.readPrevChunkAddress(PersistentHashMapValueStorage.java:655)
    at com.intellij.util.io.PersistentHashMapValueStorage.readBytes(PersistentHashMapValueStorage.java:546)
    at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:604)
    at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:545)
    at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:169)
    at org.jetbrains.kotlin.idea.search.refIndex.LookupStorageReader.get(LookupStorageReader.kt:34)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexStorage.getUsages(KotlinCompilerReferenceIndexStorage.kt:157)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService$referentFiles$1.invoke(KotlinCompilerReferenceIndexService.kt:283)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService$referentFiles$1.invoke(KotlinCompilerReferenceIndexService.kt:62)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService.tryWithReadLock(KotlinCompilerReferenceIndexService.kt:93)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService.referentFiles(KotlinCompilerReferenceIndexService.kt:264)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService.access$referentFiles(KotlinCompilerReferenceIndexService.kt:62)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService$scopeWithCodeReferences$1$1.compute(KotlinCompilerReferenceIndexService.kt:239)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService$scopeWithCodeReferences$1.invoke(KotlinCompilerReferenceIndexService.kt:237)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService$scopeWithCodeReferences$1.invoke(KotlinCompilerReferenceIndexService.kt:62)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService.runActionSafe(KotlinCompilerReferenceIndexService.kt:218)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinCompilerReferenceIndexService.scopeWithCodeReferences(KotlinCompilerReferenceIndexService.kt:236)
    at org.jetbrains.kotlin.idea.search.refIndex.KotlinScopeOptimizer.getRestrictedUseScope(KotlinScopeOptimizer.kt:10)
    at com.intellij.psi.search.ScopeOptimizer.lambda$calculateOverallRestrictedUseScope$1(ScopeOptimizer.java:53)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
    at com.intellij.psi.search.ScopeOptimizer.calculateOverallRestrictedUseScope(ScopeOptimizer.java:55)
    at com.intellij.psi.search.SearchRequestCollector.lambda$searchWord$0(SearchRequestCollector.java:61)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
    at com.intellij.psi.search.SearchRequestCollector.searchWord(SearchRequestCollector.java:61)
    at com.intellij.psi.search.SearchRequestCollector.searchWord(SearchRequestCollector.java:95)
    at org.jetbrains.plugins.groovy.findUsages.MethodLateBoundReferencesSearcher.orderSearching(MethodLateBoundReferencesSearcher.java:70)
    at org.jetbrains.plugins.groovy.findUsages.MethodLateBoundReferencesSearcher.processQuery(MethodLateBoundReferencesSearcher.java:42)
    at org.jetbrains.plugins.groovy.findUsages.MethodLateBoundReferencesSearcher.processQuery(MethodLateBoundReferencesSearcher.java:31)
    at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:77)
    at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:28)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
    at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:108)
    at com.intellij.util.MergeQuery.processResults(MergeQuery.java:22)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
    at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:108)
    at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:37)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
    at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:83)
    at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection.hasReferences(UnusedSymbolInspection.kt:487)
    at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection.hasNonTrivialUsages(UnusedSymbolInspection.kt:401)
    at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection.access$hasNonTrivialUsages(UnusedSymbolInspection.kt:87)
    at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection$buildVisitor$1.invoke(UnusedSymbolInspection.kt:298)
    at org.jetbrains.kotlin.idea.inspections.UnusedSymbolInspection$buildVisitor$1.invoke(UnusedSymbolInspection.kt:87)
    at org.jetbrains.kotlin.psi.VisitorWrappersKt$namedDeclarationVisitor$1.visitNamedDeclaration(VisitorWrappers.kt:393)
    at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedDeclaration(KtVisitorVoid.java:973)
    at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedDeclaration(KtVisitorVoid.java:21)
    at org.jetbrains.kotlin.psi.KtVisitor.visitNamedFunction(KtVisitor.java:53)
    at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:49)
    at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:491)
    at org.jetbrains.kotlin.psi.KtVisitorVoid.visitNamedFunction(KtVisitorVoid.java:21)
    at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:51)
    at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
    at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:317)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
    at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:296)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
    at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:330)
    at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
    at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
    at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:294)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
    at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:294)
    at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:297)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:282)
    at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:270)
    at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I'm running:
- IntelliJ IDEA Ultimate 2022.1.3, but also seen in 2022.1
- Version 1.21.0-RC1 plugin. Also seen in 1.20.1 and 1.20.0, possibly one or two earlier versions too but not before then.
- Windows 10

Other plugins I'm using are:
- CamelCase
- CheckStyle-IDEA
- Karma
- Maven Helper
- Prettier
- SonarLint

**Comment by arturbosch** [comment] 2022-06-29 20:47
This stacktrace looks sooo wierd with all the kotlin, intellij and even groovy references.
I'm not sure how detekt is involved with all the issues reported lately.
My guess is it has something to do with force saving the file when it does not yet exists or is synthetic ...

https://github.com/detekt/detekt-intellij-plugin/blob/307056767f32d372bead12cdc34bfda456e6c52a/src/main/kotlin/io/gitlab/arturbosch/detekt/idea/action/AutoCorrectAction.kt#L52-L60

**Comment by arturbosch** [comment] 2022-09-19 21:12
Duplicate of #271

**Closed by arturbosch** 2022-09-19 21:12 UTC
Labels: bug
