### ISSUE TITLE
org.jetbrains.kotlin.idea.caches.resolve.KotlinIdeaResolutionException: Kotlin resolution encountered a problem while getting service FileScopeProvider

### ISSUE THREAD

**Issue by mmikhulya** [detekt/detekt-intellij-plugin#339] opened 2022-10-04 08:24 UTC
Please copy paste the generated bug report## Bug description

Please include steps to reproduce expected and actual behavior.

## Environment

- detekt Idea Version: 1.21.3
- Platform Version: 2022.2.1
- Platform Vendor: JetBrains s.r.o.
- Java Version: 17.0.3
- OS Name: Mac OS X

## Stacktrace

```
org.jetbrains.kotlin.idea.caches.resolve.KotlinIdeaResolutionException: Kotlin resolution encountered a problem while getting service FileScopeProvider
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.getFrontendService(ResolutionFacadeWithDebugInfo.kt:83)
	at org.jetbrains.kotlin.idea.imports.OptimizedImportsBuilder.getFileResolutionScope(OptimizedImportsBuilder.kt:472)
	at org.jetbrains.kotlin.idea.imports.OptimizedImportsBuilder.buildScopeByImports(OptimizedImportsBuilder.kt:320)
	at org.jetbrains.kotlin.idea.imports.OptimizedImportsBuilder.addExplicitImportsForClassesWhenRequired(OptimizedImportsBuilder.kt:278)
	at org.jetbrains.kotlin.idea.imports.OptimizedImportsBuilder.tryBuildOptimizedImports(OptimizedImportsBuilder.kt:181)
	at org.jetbrains.kotlin.idea.imports.OptimizedImportsBuilder.buildOptimizedImports(OptimizedImportsBuilder.kt:100)
	at org.jetbrains.kotlin.idea.imports.KotlinImportOptimizer$Companion.prepareOptimizedImports(KotlinImportOptimizer.kt:274)
	at org.jetbrains.kotlin.idea.imports.KotlinImportOptimizer.prepareImports(KotlinImportOptimizer.kt:86)
	at org.jetbrains.kotlin.idea.imports.KotlinImportOptimizer.processFile(KotlinImportOptimizer.kt:41)
	at org.jetbrains.kotlin.idea.imports.KotlinImportOptimizer.processFile(KotlinImportOptimizer.kt:36)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor.collectOptimizers(OptimizeImportsProcessor.java:111)
	at com.intellij.codeInsight.actions.OptimizeImportsProcessor.prepareTask(OptimizeImportsProcessor.java:78)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.lambda$performFileProcessing$4(AbstractLayoutCodeProcessor.java:448)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:428)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.performFileProcessing(AbstractLayoutCodeProcessor.java:449)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$runProcessFile$0(AbstractLayoutCodeProcessor.java:291)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$2.run(AbstractLayoutCodeProcessor.java:316)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: Resolver for 'sdk with settings=PlatformAnalysisSettingsImpl(platform=JVM (11), sdk=17: java version "17.0.4" (/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home), isAdditionalBuiltInFeaturesSupported=true)' does not know how to resolve [JvmLibraryInfo(libraryName=Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.7.10, libraryRoots=[/Users/mihasik/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar])], allModules: [SdkInfo(project=Project(name=smstore-site, containerState=COMPONENT_CREATED, componentStore=/Users/mihasik/IdeaProjects/smstore-site), sdk=17: java version "17.0.4" (/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home)), SdkInfo(project=Project(name=smstore-site, containerState=COMPONENT_CREATED, componentStore=/Users/mihasik/IdeaProjects/smstore-site), sdk=Kotlin SDK ())]
	at org.jetbrains.kotlin.analyzer.DiagnoseUnknownModuleInfoReporter.errorInSdkResolver(AbstractResolverForProject.kt:314)
	at org.jetbrains.kotlin.analyzer.DiagnoseUnknownModuleInfoReporter.report(AbstractResolverForProject.kt:285)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject.diagnoseUnknownModuleInfo(AbstractResolverForProject.kt:158)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject.checkModuleIsCorrect(AbstractResolverForProject.kt:163)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject.descriptorForModule(AbstractResolverForProject.kt:149)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject.descriptorForModule(AbstractResolverForProject.kt:17)
	at org.jetbrains.kotlin.caches.resolve.JvmPlatformKindResolution$createBuiltinsFromModuleDependencies$$inlined$apply$lambda$1.invoke(JvmPlatformKindResolution.kt:112)
	at org.jetbrains.kotlin.caches.resolve.JvmPlatformKindResolution$createBuiltinsFromModuleDependencies$$inlined$apply$lambda$1.invoke(JvmPlatformKindResolution.kt:35)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getBuiltInsModule(KotlinBuiltIns.java:172)
	at org.jetbrains.kotlin.builtins.jvm.JvmBuiltIns$customizer$2.invoke(JvmBuiltIns.kt:77)
	at org.jetbrains.kotlin.builtins.jvm.JvmBuiltIns$customizer$2.invoke(JvmBuiltIns.kt:75)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
	at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:42)
	at org.jetbrains.kotlin.builtins.jvm.JvmBuiltIns.getCustomizer(JvmBuiltIns.kt:75)
	at org.jetbrains.kotlin.load.kotlin.DeserializationComponentsForJava.<init>(DeserializationComponentsForJava.kt:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jetbrains.kotlin.container.SingletonTypeComponentDescriptor.createInstanceOf(Singletons.kt:135)
	at org.jetbrains.kotlin.container.SingletonTypeComponentDescriptor.createInstance(Singletons.kt:120)
	at org.jetbrains.kotlin.container.SingletonDescriptor.createInstance(Singletons.kt:57)
	at org.jetbrains.kotlin.container.SingletonDescriptor.getValue(Singletons.kt:42)
	at org.jetbrains.kotlin.container.ComponentStorage.injectProperties(Storage.kt:155)
	at org.jetbrains.kotlin.container.ComponentStorage.composeDescriptors(Storage.kt:149)
	at org.jetbrains.kotlin.container.ComponentStorage.compose(Storage.kt:138)
	at org.jetbrains.kotlin.container.StorageComponentContainer.compose(Container.kt:58)
	at org.jetbrains.kotlin.container.DslKt.composeContainer(Dsl.kt:24)
	at org.jetbrains.kotlin.resolve.PlatformConfiguratorBaseKt.createContainer(PlatformConfiguratorBase.kt:147)
	at org.jetbrains.kotlin.frontend.java.di.InjectionKt.createContainerForLazyResolveWithJava(injection.kt:75)
	at org.jetbrains.kotlin.frontend.java.di.InjectionKt.createContainerForLazyResolveWithJava$default(injection.kt:56)
	at org.jetbrains.kotlin.resolve.jvm.JvmResolverForModuleFactory.createResolverForModule(JvmResolverForModuleFactory.kt:107)
	at org.jetbrains.kotlin.idea.caches.resolve.IdeaResolverForProject.createResolverForModule(IdeaResolverForProject.kt:125)
	at org.jetbrains.kotlin.idea.caches.resolve.IdeaResolverForProject.createResolverForModule(IdeaResolverForProject.kt:42)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject$resolverForModuleDescriptorImpl$1.invoke(AbstractResolverForProject.kt:138)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject$resolverForModuleDescriptorImpl$1.invoke(AbstractResolverForProject.kt:125)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager.compute(LockBasedStorageManager.java:290)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject.resolverForModuleDescriptorImpl(AbstractResolverForProject.kt:125)
	at org.jetbrains.kotlin.analyzer.AbstractResolverForProject.resolverForModuleDescriptor(AbstractResolverForProject.kt:96)
	at org.jetbrains.kotlin.analyzer.ResolverForProject.resolverForModule(AnalyzerFacade.kt:45)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.resolverForModuleInfo$kotlin_core(ProjectResolutionFacade.kt:136)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.getFrontendService(ModuleResolutionFacadeImpl.kt:115)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.getFrontendService(ModuleResolutionFacadeImpl.kt:98)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.getFrontendService(ResolutionFacadeWithDebugInfo.kt:84)
	... 55 more
```

**Comment by arturbosch** [comment] 2023-08-15 11:13
Duplicate of #271

**Closed by arturbosch** 2023-08-15 11:13 UTC
