### ISSUE TITLE
Run autocorrect only when save is trigerred

### ISSUE THREAD

**Issue by satyarths** [detekt/detekt-intellij-plugin#53] opened 2019-11-25 09:35 UTC
Right now autocorrect runs on the file by default. This conflicts with the User actions like adding braces, adding empty spaces etc. Would it be possible to trigger auto correct only when the file is being  closed and/or manually saved.

**Comment by dlyahov** [comment] 2019-11-30 15:26
I think, better to remove auto-formatting at all, assign it to some action in the IDEA in order to users call it manually.
Because of auto-formatting cause issues like this. 
![image](https://user-images.githubusercontent.com/8529665/69902394-ee763300-1395-11ea-82bf-a1e2dc4dc0d5.png)

When I removed code which makes auto-formatting this issue becomes non-producible

This action allows users to assign it to hot-key in IDEA, and users will use it when they want.

**Comment by dlyahov** [comment] 2019-12-10 07:06
@arturbosch @satyarths here is PR to disable automatical AutoCorrect functionality and moving it to IDEA action #55

**Closed** 2019-12-15 18:52 UTC
Labels: good first issue, help wanted, improvement

**Comment by JavierSegoviaCordoba** [comment] 2020-04-03 00:26
Is there any way to use detekt autoCorrect with the reformat hotkey (cmd opt L - control alt L)?

**Comment by arturbosch** [comment] 2020-04-06 09:55
Unfortunately no one I know. You could configure a custom hotkey.
The save actions plugin (https://github.com/dubreuia/intellij-plugin-save-actions#editor-actions)
supports running arbitrary actions but only for Java plugins I guess.

**Comment by JavierSegoviaCordoba** [comment] 2020-04-06 12:22
The problem is detekt plugin only works with the open file. Reformat code can works for multiple file, for example if I select a package, all files will be formated. Should be great to get the same behavior in detekt.

**Comment by arturbosch** [comment] 2020-04-06 18:26
@JavierSegoviaCordoba feel free to vote on that issue https://github.com/detekt/detekt-intellij-plugin/issues/34 and create ones for new ideas.
