### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid type variable (must not contain . ; [ / < > or :): <no name provided>

### ISSUE THREAD

**Issue by panos-geladaris** [detekt/detekt-intellij-plugin#340] opened 2022-10-04 21:21 UTC
## Bug description

Opening right click menu on the project folder, creating a kt class file and defining a sealed class.

## Environment

- detekt Idea Version: 1.21.2
- Platform Version: 2022.2.1
- Platform Vendor: JetBrains s.r.o.
- Java Version: 17.0.3
- OS Name: Mac OS X

## Stacktrace

```
java.lang.IllegalArgumentException: Invalid type variable (must not contain . ; [ / < > or :): <no name provided>
	at org.jetbrains.org.objectweb.asm.util.CheckSignatureAdapter.checkIdentifier(CheckSignatureAdapter.java:355)
	at org.jetbrains.org.objectweb.asm.util.CheckSignatureAdapter.visitTypeVariable(CheckSignatureAdapter.java:263)
	at org.jetbrains.kotlin.codegen.signature.BothSignatureWriter.writeTypeVariable(BothSignatureWriter.java:154)
	at org.jetbrains.kotlin.codegen.signature.BothSignatureWriter.writeTypeVariable(BothSignatureWriter.java:30)
	at org.jetbrains.kotlin.load.kotlin.DescriptorBasedTypeSignatureMappingKt.mapType(descriptorBasedTypeSignatureMapping.kt:157)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.kt:276)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$writeGenericArguments$1$1.invoke(KotlinTypeMapper.kt:367)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$writeGenericArguments$1$1.invoke(KotlinTypeMapper.kt:366)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$Companion.writeGenericArguments(KotlinTypeMapper.kt:1499)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeGenericArguments(KotlinTypeMapper.kt:366)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeGenericArguments(KotlinTypeMapper.kt:356)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.writeGenericType(KotlinTypeMapper.kt:309)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.access$writeGenericType(KotlinTypeMapper.kt:84)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$mapType$1.invoke(KotlinTypeMapper.kt:279)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$mapType$1.invoke(KotlinTypeMapper.kt:276)
	at org.jetbrains.kotlin.load.kotlin.DescriptorBasedTypeSignatureMappingKt.mapType(descriptorBasedTypeSignatureMapping.kt:145)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.kt:276)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapReturnType(KotlinTypeMapper.kt:218)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapReturnType(KotlinTypeMapper.kt:201)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapSignatureWithCustomParameters(KotlinTypeMapper.kt:915)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapSignature(KotlinTypeMapper.kt:828)
	at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapSignatureWithGeneric(KotlinTypeMapper.kt:772)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy.mapMethodSignature(FunctionGenerationStrategy.java:46)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:189)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:166)
	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen$DataClassMethodGeneratorImpl.generateCopyFunction(ImplementationBodyCodegen.java:640)
	at org.jetbrains.kotlin.backend.common.DataClassMethodGenerator.generateCopyFunctionForDataClasses(DataClassMethodGenerator.kt:61)
	at org.jetbrains.kotlin.backend.common.DataClassMethodGenerator.generate(DataClassMethodGenerator.kt:37)
	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateFunctionsForDataClasses(ImplementationBodyCodegen.java:560)
	at org.jetbrains.kotlin.codegen.ImplementationBodyCodegen.generateSyntheticPartsAfterBody(ImplementationBodyCodegen.java:434)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:135)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:305)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:289)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForClassOrObject$computeLightClassData$1$1.invoke(LightClassDataProvider.kt:52)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForClassOrObject$computeLightClassData$1$1.invoke(LightClassDataProvider.kt:47)
	at org.jetbrains.kotlin.asJava.builder.LightClassBuilderKt.buildLightClass(LightClassBuilder.kt:65)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForClassOrObject$computeLightClassData$1.invoke(LightClassDataProvider.kt:47)
	at org.jetbrains.kotlin.asJava.builder.LightClassDataProviderForClassOrObject$computeLightClassData$1.invoke(LightClassDataProvider.kt:45)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$_builderExactContextProvider$2.invoke(LazyLightClassDataHolder.kt:44)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$_builderExactContextProvider$2.invoke(LazyLightClassDataHolder.kt:30)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder.get_builderExactContextProvider(LazyLightClassDataHolder.kt)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder.access$get_builderExactContextProvider$p(LazyLightClassDataHolder.kt:30)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$extraDiagnostics$1.invoke(LazyLightClassDataHolder.kt:61)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$extraDiagnostics$1.invoke(LazyLightClassDataHolder.kt:30)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$CacheWithNullableValuesBasedOnMemoizedFunction$1.invoke(LockBasedStorageManager.java:693)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$CacheWithNullableValuesBasedOnMemoizedFunction$1.invoke(LockBasedStorageManager.java:690)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$CacheWithNullableValuesBasedOnMemoizedFunction.computeIfAbsent(LockBasedStorageManager.java:701)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$CacheWithNotNullValuesBasedOnMemoizedFunction.computeIfAbsent(LockBasedStorageManager.java:723)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder$DiagnosticsHolder.getOrCompute(LazyLightClassDataHolder.kt:41)
	at org.jetbrains.kotlin.idea.caches.lightClasses.LazyLightClassDataHolder.getExtraDiagnostics(LazyLightClassDataHolder.kt:58)
	at org.jetbrains.kotlin.asJava.DuplicateJvmSignatureUtilKt.getJvmSignatureDiagnostics$getDiagnosticsForClass(duplicateJvmSignatureUtil.kt:55)
	at org.jetbrains.kotlin.asJava.DuplicateJvmSignatureUtilKt.getJvmSignatureDiagnostics$doGetDiagnostics(duplicateJvmSignatureUtil.kt:74)
	at org.jetbrains.kotlin.asJava.DuplicateJvmSignatureUtilKt.getJvmSignatureDiagnostics(duplicateJvmSignatureUtil.kt:92)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor$DuplicateJvmSignatureAnnotator.annotate(AbstractKotlinHighlightVisitor.kt:245)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor$DuplicateJvmSignatureAnnotator.access$annotate(AbstractKotlinHighlightVisitor.kt:227)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor$DuplicateJvmSignatureAnnotator$visit$1.visitElement(AbstractKotlinHighlightVisitor.kt:236)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:52)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:41)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor$DuplicateJvmSignatureAnnotator$visit$1.visitElement(AbstractKotlinHighlightVisitor.kt:237)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitFile(PsiRecursiveElementVisitor.java:60)
	at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:238)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor$DuplicateJvmSignatureAnnotator.visit(AbstractKotlinHighlightVisitor.kt:234)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.annotateDuplicateJvmSignature(AbstractKotlinHighlightVisitor.kt:166)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:142)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:63)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:221)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by arturbosch** [comment] 2023-08-15 11:13
Duplicate of #271

**Closed by arturbosch** 2023-08-15 11:13 UTC
