### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by mmikhulya** [detekt/detekt-intellij-plugin#345] opened 2022-10-10 08:58 UTC
## Bug description

Error appeared after merging conflicts.

## Environment

- detekt Idea Version: 1.21.3
- Platform Version: 2022.2.1
- Platform Vendor: JetBrains s.r.o.
- Java Version: 17.0.3
- OS Name: Mac OS X

## Stacktrace

```
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:65)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:215)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:937)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:744)
	at com.intellij.psi.util.PsiTreeUtil.getChildOfType(PsiTreeUtil.java:332)
	at org.jetbrains.kotlin.psi.KtFile.getScript(KtFile.kt:287)
	at com.android.tools.idea.gradle.dsl.parser.kotlin.KotlinDslParser.parse(KotlinDslParser.kt:101)
	at com.android.tools.idea.gradle.dsl.parser.files.GradleDslFile.parse(GradleDslFile.java:156)
	at com.android.tools.idea.gradle.dsl.model.BuildModelContext.lambda$parseBuildFile$1(BuildModelContext.java:213)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
	at com.android.tools.idea.gradle.dsl.model.BuildModelContext.parseBuildFile(BuildModelContext.java:208)
	at com.android.tools.idea.gradle.dsl.parser.files.GradleDslFileCache.getOrCreateBuildFile(GradleDslFileCache.java:65)
	at com.android.tools.idea.gradle.dsl.model.BuildModelContext.getOrCreateBuildFile(BuildModelContext.java:172)
	at com.android.tools.idea.gradle.dsl.model.BuildModelContext.getOrCreateBuildFile(BuildModelContext.java:177)
	at com.android.tools.idea.gradle.dsl.model.ProjectBuildModelImpl.getModuleBuildModel(ProjectBuildModelImpl.java:91)
	at com.android.tools.idea.gradle.dsl.model.ProjectBuildModelImpl.getModuleBuildModel(ProjectBuildModelImpl.java:70)
	at org.jetbrains.plugins.gradle.dsl.GradleDependencyModificator.declaredDependencies(GradleDependencyModificator.kt:149)
	at com.intellij.externalSystem.DependencyModifierService$declaredDependencies$1.invoke(DependencyModifierService.kt:26)
	at com.intellij.externalSystem.DependencyModifierService$declaredDependencies$1.invoke(DependencyModifierService.kt:15)
	at com.intellij.externalSystem.DependencyModifierService.read(DependencyModifierService.kt:60)
	at com.intellij.externalSystem.DependencyModifierService.declaredDependencies(DependencyModifierService.kt:25)
	at org.jetbrains.security.model.impl.ProjectDependenciesModelImpl$getDeclaredDependencies$smartReadAction$1.invoke(ProjectDependenciesModelImpl.kt:87)
	at org.jetbrains.security.model.impl.ProjectDependenciesModelImpl$getDeclaredDependencies$smartReadAction$1.invoke(ProjectDependenciesModelImpl.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:96)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:81)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:13)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:14)
	at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:111)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$2$1.run(cancellableReadAction.kt:33)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$2.run(cancellableReadAction.kt:31)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:29)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:80)
	at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:66)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:13)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:14)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:138)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:61)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by arturbosch** [comment] 2023-01-16 18:57
Duplicate of #271

**Closed by arturbosch** 2023-01-16 18:57 UTC
