### ISSUE TITLE
io.github.detekt.tooling.api.InvalidConfig: [31mRun failed with 1 invalid config property.[0m

### ISSUE THREAD

**Issue by mbalajee** [detekt/detekt-intellij-plugin#187] opened 2022-06-22 19:10 UTC
## Bug description
Please include steps to reproduce expected and actual behavior.

## Environment
- detekt Idea Version: 1.21.0-RC1
- Platform Version: Chipmunk | 2021.2.1
- Platform Vendor: JetBrains s.r.o.
- Java Version: 11.0.12
- OS Name: Mac OS X

## Stacktrace

```
io.github.detekt.tooling.api.InvalidConfig: [31mRun failed with 1 invalid config property.[0m
	- [33mProperty 'formatting>Indentation>continuationIndentSize' is deprecated. `continuationIndentSize` is ignored by KtLint and will have no effect.[0m
	- [31mProperty 'formatting>NoItParamInMultilineLambda' is misspelled or does not exist.[0m
	- [33mProperty 'formatting>ParameterListWrapping>indentSize' is deprecated. `indentSize` is ignored by KtLint and will have no effect.[0m
	- [33mProperty 'complexity>LongParameterList>threshold' is deprecated. Use `functionThreshold` and `constructorThreshold` instead.[0m
	- [33mProperty 'exceptions>ThrowingExceptionsWithoutMessageOrCause>exceptions' should be a YAML array instead of a comma-separated String.[0m
	- [33mProperty 'naming>ForbiddenClassName>forbiddenName' should be a YAML array instead of a comma-separated String.[0m
	- [33mProperty 'potential-bugs>LateinitUsage>excludeAnnotatedProperties' is deprecated. Use `ignoreAnnotated` instead.[0m
	- [33mProperty 'style>ForbiddenComment>values' should be a YAML array instead of a comma-separated String.[0m
	- [33mProperty 'style>ForbiddenImport>imports' should be a YAML array instead of a comma-separated String.[0m
	- [33mProperty 'style>ForbiddenMethodCall>methods' should be a YAML array instead of a comma-separated String.[0m
	- [33mProperty 'style>ForbiddenPublicDataClass>ignorePackages' should be a YAML array instead of a comma-separated String.[0m
	- [33mProperty 'style>FunctionOnlyReturningConstant>excludeAnnotatedFunction' is deprecated. Use `ignoreAnnotated` instead.[0m
	- [33mProperty 'style>MagicNumber>ignoreNumbers' should be a YAML array instead of a comma-separated String.[0m
	- [33mProperty 'style>UnderscoresInNumericLiterals>acceptableDecimalLength' is deprecated. Use `acceptableLength` instead.[0m
	- [33mProperty 'style>UnnecessaryAbstractClass>excludeAnnotatedClasses' is deprecated. Use `ignoreAnnotated` instead.[0m
	- [33mProperty 'style>UseDataClass>excludeAnnotatedClasses' is deprecated. Use `ignoreAnnotated` instead.[0m
	- [33mProperty 'style>WildcardImport>excludeImports' should be a YAML array instead of a comma-separated String.[0m
	at io.gitlab.arturbosch.detekt.core.config.ConfigValidatorsKt.checkConfiguration(ConfigValidators.kt:27)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$1.invoke(Lifecycle.kt:37)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$1.invoke(Lifecycle.kt:37)
	at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:34)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:37)
	at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:61)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:48)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:47)
	at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:26)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:47)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:33)
	at io.gitlab.arturbosch.detekt.idea.ConfiguredService$execute$$inlined$runWriteAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:945)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:945)
	at io.gitlab.arturbosch.detekt.idea.ConfiguredService.execute(ConfiguredService.kt:138)
	at io.gitlab.arturbosch.detekt.idea.ConfiguredService.execute(ConfiguredService.kt:92)
	at io.gitlab.arturbosch.detekt.idea.action.AutoCorrectAction.runAction$detekt_intellij_plugin(AutoCorrectAction.kt:49)
	at io.gitlab.arturbosch.detekt.idea.action.AutoCorrectAction.actionPerformed(AutoCorrectAction.kt:38)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$performAction$0(ActionMenuItem.java:277)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.performAction(ActionMenuItem.java:269)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:81)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by schalkms** [comment] 2022-06-29 10:01
duplicate of #179

As a workaround, you @mbalajee can disable the config validation in the detekt config yaml file as follows.

```yaml
config:
  validation: false
```

**Closed by schalkms** 2022-06-29 10:01 UTC
Labels: duplicate
