### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by MrTomato** [detekt/detekt-intellij-plugin#201] opened 2022-07-06 14:44 UTC
## Bug description
Unshelve changes

## Environment
- detekt Idea Version: 1.21.0-RC2
- Platform Version: 2022.1.3
- Platform Vendor: JetBrains s.r.o.
- Java Version: 11.0.15
- OS Name: Mac OS X

## Stacktrace

```
Outdated stub in index: file:///Users/mfischer/coding/cofa/service-customer-onboarding-api/src/test/kotlin/de/dkb/api/customeronboarding/domain/pega/PegaCaseTest.kt indexing timestamp = 1657118574699, binary = false, byte size = 23564, char size = 0, doc=DocumentImpl[file:///Users/mfischer/coding/cofa/service-customer-onboarding-api/src/test/kotlin/de/dkb/api/customeronboarding/domain/pega/PegaCaseTest.kt], docSaved=true, wasIndexedAlready=true, queried at 1657118574699
doc length=23564
file length=23564
cached PSI class org.jetbrains.kotlin.psi.KtFile
projects with file: 2
physical file exists; length = 23564

java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:191)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:157)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:124)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:49)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:634)
	at com.intellij.psi.impl.source.PsiFileImpl.getStub(PsiFileImpl.java:597)
	at org.jetbrains.kotlin.psi.KtFile.getStub(KtFile.kt:194)
	at org.jetbrains.kotlin.psi.KtFile.isScript(KtFile.kt:217)
	at org.jetbrains.kotlin.idea.caches.resolve.KtFileClassProviderImpl$getFileClasses$$inlined$runReadAction$1.compute(definitions.kt:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at org.jetbrains.kotlin.idea.caches.resolve.KtFileClassProviderImpl.getFileClasses(KtFileClassProviderImpl.kt:61)
	at org.jetbrains.kotlin.psi.KtFile.getClasses(KtFile.kt:204)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider.doModify(ClassesTreeStructureProvider.java:77)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider.lambda$modify$0(ClassesTreeStructureProvider.java:44)
	at com.intellij.ide.util.treeView.AbstractTreeUi.calculateYieldingToWriteAction(AbstractTreeUi.java:1715)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider.modify(ClassesTreeStructureProvider.java:44)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:49)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:383)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:299)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:293)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:313)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:545)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:314)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:203)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:181)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:481)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by arturbosch** [comment] 2022-09-18 19:59
Duplicate of #271

**Closed by arturbosch** 2022-09-18 19:59 UTC
Labels: bug
