### ISSUE TITLE
Installation issue, plugin doesn't seem to be installed

### ISSUE THREAD

**Issue by CapnSpellcheck** [detekt/detekt-intellij-plugin#156] opened 2022-03-10 22:35 UTC
After installing the plugin from the Marketplace, and closing and relaunching Studio, the plugin is not listed under installed plugins. I search for Detekt again and it shows Install button again. Further, no Detekt settings show up on the preferences window.

Using Android Studio Bumblebee | 2021.1.1 Patch 1 on macOS.

**Comment by arturbosch** [comment] 2022-05-26 08:53
Hi,
were you able to reproduce this strange behavior?

Are there any errors thrown?
Is there something strange in the idea log (Action: `Show log in files`) ?

**Comment by CapnSpellcheck** [comment] 2022-05-27 02:13
This isn't blocking me, I tried again a few times and restarted the app and eventually it worked.

**Comment by arturbosch** [comment] 2022-05-28 17:13
I'm closing this as I do not think it did happen due to our plugin but an IDEA internal error.
Feel free to reopen if this happens again with a stacktrace in the idea.log file.

**Closed by arturbosch** 2022-05-28 17:13 UTC
Labels: support
