### ISSUE TITLE
com.intellij.diagnostic.PluginException: annotator: io.gitlab.arturbosch.detekt.idea.DetektAnnotator@1de8f166 (class io.gitlab.arturbosch.detekt.idea.DetektAnnotator) [Plugin: detekt]

### ISSUE THREAD

**Issue by jvorhauer** [detekt/detekt-intellij-plugin#272] opened 2022-08-22 15:16 UTC
## Steps to reproduce:

Open project with non-default config/detekt.yml. No user-action required.

## Bug description

Please include steps to reproduce expected and actual behavior.

## Environment

- detekt Idea Version: 1.21.1
- Platform Version: 2022.2.1
- Platform Vendor: JetBrains s.r.o.
- Java Version: 17.0.3
- OS Name: Mac OS X

## Stacktrace

```
com.intellij.diagnostic.PluginException: annotator: io.gitlab.arturbosch.detekt.idea.DetektAnnotator@1de8f166 (class io.gitlab.arturbosch.detekt.idea.DetektAnnotator) [Plugin: detekt]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:274)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:223)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:214)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:192)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:289)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:191)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:332)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:322)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:285)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:240)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:388)
	at com.intellij.util.Alarm$Request.run(Alarm.java:377)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Configuration must be a file: /Users/juvor/Code/kotlin/rtmp
	at io.gitlab.arturbosch.detekt.core.config.YamlConfig$Companion.load(YamlConfig.kt:55)
	at io.gitlab.arturbosch.detekt.core.config.ConfigurationsKt.parsePathConfig(Configurations.kt:43)
	at io.gitlab.arturbosch.detekt.core.config.ConfigurationsKt.loadConfiguration(Configurations.kt:16)
	at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt$withSettings$configuration$1.invoke(ProcessingSpecSettingsBridge.kt:16)
	at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt$withSettings$configuration$1.invoke(ProcessingSpecSettingsBridge.kt:16)
	at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
	at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:16)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:47)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:33)
	at io.gitlab.arturbosch.detekt.idea.ConfiguredService.execute(ConfiguredService.kt:121)
	at io.gitlab.arturbosch.detekt.idea.ConfiguredService.execute(ConfiguredService.kt:107)
	at io.gitlab.arturbosch.detekt.idea.DetektAnnotator.doAnnotate(DetektAnnotator.kt:38)
	at io.gitlab.arturbosch.detekt.idea.DetektAnnotator.doAnnotate(DetektAnnotator.kt:18)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:220)
	... 37 more
```

**Comment by arturbosch** [comment] 2022-08-23 08:10
Hi, was this a fresh IDE with first time installed detekt plugin?

**Comment by arturbosch** [comment] 2022-08-23 10:42
Hey @rock3r,
I'm having a hard time finding out how this state can happen:

![Screenshot from 2022-08-23 12-40-27](https://user-images.githubusercontent.com/20924106/186138362-a62cf86d-bfe0-4f01-a9ca-e4c23288fbcc.png)

IJ 2022.2 with installed detekt plugin, opening a new project which was previously not in the "recent projects" list and has no default `config/detekt.yaml` folder.

Do you have an idea?

**Comment by rock3r** [comment] 2022-08-23 10:46
Huh this is SO odd. Maybe something in the code that in absence of a valid configuration file falls back to the user home?

**Comment by rock3r** [comment] 2022-08-23 15:17
I'm going to try to fix it later 🤞 but can't make promises

**Comment by arturbosch** [comment] 2022-08-23 16:16
> Huh this is SO odd. Maybe something in the code that in absence of a valid configuration file falls back to the user home?

No, just 
```kotlin
private fun configPaths(): List<Path> =
        settings.configurationFilePaths
            .asSequence()
            .asAbsolutePaths()
            .toList()

```

is called and directly passed to detekt-core

> 
> Can you repro this on Windows or macOS? I had tested on both those and didn't have this issue, but maybe something changed since then.

I can't test it on Windows or MacOS myself.

The issue is not directly reproducable.
I had an already running IDE with an installed plugin and opened a project I had not opened in a while (It was not in my IDE recent project list).
Before that I opened the same project in a fresh `gradle runIde` and the error did not occurr :O.
Super strange.

I haven't changed any UI code since your PR. Just removed the OldConfigurationUI and the bug reports started with the new version 1.21.1 and the new UI.

> I'm going to try to fix it later crossed_fingers but can't make promises

Thanks you 🙏🏼

**Comment by rock3r** [comment] 2022-08-23 16:26
I have a sneaking suspicion the `asAbsolutePaths()` may be the culprit here, maybe we need to add a `filter { it.isNotEmpty}` to the sequence before that

**Comment by arturbosch** [comment] 2022-08-23 16:54
> I have a sneaking suspicion the `asAbsolutePaths()` may be the culprit here, maybe we need to add a `filter { it.isNotBlank() }` to the sequence before that

Mh I think it is part of it:

Calling `settings.configurationFilePaths` will return a set with one empty string element

So this code somehow returns a 1 element set:

```
var configurationFilePaths by stringSet()
```

**Comment by rock3r** [comment] 2022-08-23 16:59
@arturbosch can you test on the PR branch? I couldn't repro but that should fix it

**Comment by arturbosch** [comment] 2022-08-23 17:03
> @arturbosch can you test on the PR branch? I couldn't repro but that should fix it

Yes, it will fix. 
I've found the root cause:

Whenever I start a test / fresh IDE the migration logic is run:
```kotlin
            configurationFilePaths = oldSettings.configPaths.split(File.pathSeparator).toMutableSet()
            pluginJarPaths = oldSettings.pluginPaths.split(File.pathSeparator).toMutableSet()
```

these two lines with produce a set of one empty string element from `""`

**Comment by rock3r** [comment] 2022-08-23 17:07
I had just found that and pushed a fix :) I didn't test the migration scenario after some other changes, I think that was why I didn't detect the issue.

**Closed** 2022-08-23 17:18 UTC
Labels: bug
