### ISSUE TITLE
com.intellij.psi.stubs.ManyProjectsStubIndexMismatch: PSI and index do not match.

### ISSUE THREAD

**Issue by AShynkevich** [detekt/detekt-intellij-plugin#303] opened 2022-09-02 06:26 UTC
## Bug description

Please include steps to reproduce expected and actual behavior.

## Environment

- detekt Idea Version: 1.21.3
- Platform Version: 2022.2.1
- Platform Vendor: JetBrains s.r.o.
- Java Version: 17.0.3
- OS Name: Mac OS X

## Stacktrace

```
com.intellij.psi.stubs.ManyProjectsStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PsiFile:JndiConnectionFactoryAutoConfiguration.class, file.class=class com.intellij.psi.impl.compiled.ClsFileImpl, file.lang=Language: JAVA, modStamp=0
 stub debugInfo=created from file content; with backReference
latestIndexedStub=null
 viewProvider=com.intellij.psi.ClassFileViewProvider{vFile=jar:///Users/Aliaksandr_Shynkevic/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.7.2/f358e3f8ce01d3a26605fa23f9d3fd408726b033/spring-boot-autoconfigure-2.7.2.jar!/org/springframework/boot/autoconfigure/jms/JndiConnectionFactoryAutoConfiguration.class, vFileId=68707, content=VirtualFileContent{size=3302}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1658480653776; file length: 3302
indexing info: null
	at com.intellij.psi.stubs.StubTreeLoader.handleManyProjectsMismatch(StubTreeLoader.java:140)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:65)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:151)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:93)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:72)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:138)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:185)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
	at com.intellij.psi.impl.java.stubs.index.JavaAnnotationIndex.get(JavaAnnotationIndex.java:30)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.lambda$getAnnotationCandidates$3(AnnotatedElementsSearcher.java:72)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.getAnnotationCandidates(AnnotatedElementsSearcher.java:70)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:35)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:21)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:28)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:108)
	at com.intellij.util.InstanceofQuery.processResults(InstanceofQuery.java:22)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:83)
	at com.intellij.codeInsight.MetaAnnotationUtil.getChildren(MetaAnnotationUtil.java:147)
	at com.intellij.codeInsight.MetaAnnotationUtil.collectClassWithChildren(MetaAnnotationUtil.java:235)
	at com.intellij.codeInsight.MetaAnnotationUtil.findAnnotationTypesWithChildren(MetaAnnotationUtil.java:186)
	at com.intellij.codeInsight.MetaAnnotationUtil.lambda$getLibraryAnnotationClassesMap$4(MetaAnnotationUtil.java:127)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.codeInsight.MetaAnnotationUtil.getChildLibraryAnnotations(MetaAnnotationUtil.java:100)
	at com.intellij.codeInsight.MetaAnnotationUtil.lambda$getAllAnnotationClassesMap$0(MetaAnnotationUtil.java:83)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:65)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypes(JamAnnotationTypeUtilImpl.java:135)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypesWithChildren(JamAnnotationTypeUtilImpl.java:124)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$CustomMetaAnnotationsFunction.getAnnotationTypes(SpringSemContributorUtil.java:325)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$CustomMetaAnnotationsFunction.fun(SpringSemContributorUtil.java:283)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$CustomMetaAnnotationsFunction.fun(SpringSemContributorUtil.java:268)
	at com.intellij.spring.model.jam.SpringSemContributorUtil.lambda$createFunction$2(SpringSemContributorUtil.java:109)
	at com.intellij.semantic.SemRegistrar.lambda$registerSemElementProvider$0(SemRegistrar.java:27)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:129)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:100)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:86)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:32)
	at com.intellij.spring.model.jam.SpringSemContributorUtil.lambda$registerMetaComponents$0(SpringSemContributorUtil.java:56)
	at com.intellij.semantic.SemRegistrar.lambda$registerSemElementProvider$0(SemRegistrar.java:27)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:129)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:100)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:86)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:32)
	at com.intellij.jam.JamService.getJamElement(JamService.java:102)
	at com.intellij.spring.model.highlighting.jam.ContextJavaBeanUnresolvedMethodsInspection.getContextJavaBean(ContextJavaBeanUnresolvedMethodsInspection.java:90)
	at com.intellij.spring.model.highlighting.jam.ContextJavaBeanUnresolvedMethodsInspection.checkMethod(ContextJavaBeanUnresolvedMethodsInspection.java:52)
	at com.intellij.spring.model.highlighting.jam.ContextJavaBeanUnresolvedMethodsInspection.checkClass(ContextJavaBeanUnresolvedMethodsInspection.java:45)
	at com.intellij.codeInspection.AbstractBaseUastLocalInspectionTool$1.visitClass(AbstractBaseUastLocalInspectionTool.java:73)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:43)
	at com.intellij.uast.UastHintedVisitorAdapter.visitElement(UastHintedVisitorAdapter.kt:21)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:52)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:317)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:325)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:331)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:294)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:294)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:297)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:282)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:270)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by arturbosch** [comment] 2022-09-05 14:26
Duplicate of #271

**Closed by arturbosch** 2022-09-05 14:26 UTC
